# ── Audit ledger dataset + table ──────────────────────────────────────────────
# Application-level audit trail. grant_access and revoke_access write directly
# to this table via the BigQuery client — one row per lifecycle event
# (GRANT, DENY, REVOKE), never an UPDATE. Treating it as an append-only ledger
# means the audit trail can't be quietly edited after the fact, which is the
# property SOX 404 ITGC evidence actually needs.
resource "google_bigquery_dataset" "audit" {
  dataset_id    = var.audit_dataset_id
  friendly_name = "BankVault JIT access audit ledger"
  description   = "Append-only ledger of every grant, denial, and revocation issued by the BankVault JIT broker."
  location      = var.bq_location

  labels = local.common_labels

  depends_on = [google_project_service.apis]
}

resource "google_bigquery_table" "access_grants" {
  dataset_id          = google_bigquery_dataset.audit.dataset_id
  table_id            = var.audit_table_id
  deletion_protection = false

  time_partitioning {
    type  = "DAY"
    field = "event_timestamp"
  }

  clustering = ["request_id", "action_type"]

  schema = jsonencode([
    {
      name        = "request_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "UUID generated by grant_access at request time. Links GRANT, DENY, and REVOKE rows for the same request."
    },
    {
      name        = "action_type"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "One of GRANT, DENY, REVOKE."
    },
    {
      name        = "requested_by"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Email of the loan officer requesting access (who)."
    },
    {
      name        = "resource"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Fully-qualified resource the grant applies to, e.g. gs://<bucket>/<loan-application-id-prefix> (what resource)."
    },
    {
      name        = "justification"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Business justification supplied with the request, e.g. loan application ID being processed."
    },
    {
      name        = "window_start"
      type        = "TIMESTAMP"
      mode        = "NULLABLE"
      description = "Start of the requested access window (what window)."
    },
    {
      name        = "window_end"
      type        = "TIMESTAMP"
      mode        = "NULLABLE"
      description = "End of the requested access window — the CEL condition's request.time upper bound (what window)."
    },
    {
      name        = "approved_by"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Identity or policy that approved the request (who/what approved). 'policy:auto-approved' when approval is automatic under the configured rules."
    },
    {
      name        = "granted_at"
      type        = "TIMESTAMP"
      mode        = "NULLABLE"
      description = "Timestamp the IAM binding was actually applied (when granted)."
    },
    {
      name        = "revoked_at"
      type        = "TIMESTAMP"
      mode        = "NULLABLE"
      description = "Timestamp the IAM binding was removed by the revocation sweep (when revoked). NULL on GRANT/DENY rows."
    },
    {
      name        = "iam_condition_expression"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "The exact CEL expression attached to the IAM binding, kept for audit reproducibility."
    },
    {
      name        = "session_secret_name"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Secret Manager resource name holding the session token for this grant. Never the token value itself."
    },
    {
      name        = "denial_reason"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Populated on DENY rows: why the request was rejected (domain check, duration cap, missing approver, self-approval, etc.)."
    },
    {
      name        = "event_timestamp"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "When this ledger row was written. Partition key."
    },
  ])

  labels = local.common_labels
}

# ── Platform log export ───────────────────────────────────────────────────────
# Separate from the application-level ledger above: this is the raw Cloud
# Logging export for both functions' execution logs (invocations, errors,
# cold starts). It exists because SOX/FFIEC evidence shouldn't depend
# entirely on application code behaving correctly — if grant_access has a
# bug and skips a ledger write, the platform-level invocation log still
# exists as a second, independently-produced record.
resource "google_bigquery_dataset" "platform_logs" {
  dataset_id    = var.platform_logs_dataset_id
  friendly_name = "BankVault Cloud Function execution logs"
  description   = "Raw Cloud Logging export for the grant_access and revoke_access functions, routed via the log sink below."
  location      = var.bq_location

  labels = local.common_labels

  depends_on = [google_project_service.apis]
}

resource "google_logging_project_sink" "function_logs_to_bq" {
  name        = "bankvault-function-logs-sink"
  description = "Routes grant_access and revoke_access Cloud Run (Cloud Functions v2) execution logs to BigQuery for durable retention."

  destination = "bigquery.googleapis.com/projects/${var.project_id}/datasets/${google_bigquery_dataset.platform_logs.dataset_id}"

  filter = <<-EOT
    resource.type="cloud_run_revision"
    (resource.labels.service_name="${var.grant_function_name}" OR resource.labels.service_name="${var.revoke_function_name}")
  EOT

  unique_writer_identity = true

  bigquery_options {
    use_partitioned_tables = true
  }
}

# The sink writes as its own service identity, not as either function's SA —
# that identity needs explicit write access to the destination dataset.
resource "google_bigquery_dataset_iam_member" "sink_writer" {
  dataset_id = google_bigquery_dataset.platform_logs.dataset_id
  role       = "roles/bigquery.dataEditor"
  member     = google_logging_project_sink.function_logs_to_bq.writer_identity
}
